### ISSUE TITLE
Question: Can we force a mapping to _not_ have soft-clippings?

### ISSUE THREAD

**Issue by holtjma** [jguhlin/minimap2-rs#67]
Hey @jguhlin,

Apologies if this is a naive question: I'm wondering if there's a programmatic way to tell the mapper _not_ to allow soft-clippings, and to instead force the alignment of the ends (even if it's "bad"). I have a situation where there is a variant near the end of a sequence I'm mapping (within 3bp), and I'd like it to still map that component without clipping.  Instead, it's soft-clipping the whole 3bp piece.  

I think I can come behind and hack a mini-aligner for that fragment, but I was hoping there was some programmatic way to disable soft-clipping within the interface. Is there some hidden parameter in the `MapOpt` that might control this? Or is there some parameter controlling to cost of soft-clipping that I can set super higher? Or some other idea that will get the same desired result?

Matt

**Comment by jrharting** [comment]
hey Matt,

I was able to handle this HLA by increasing the match score.  None of my
tests changed in that case, but you would want to check.

22  /// Slightly modified Aligner for longer sequences
   23  /// Increasing only the matching score from 1 ->2 for map-hifi
because it seems
   24  /// to capture the last couple bases when there is a mismatch at the
end
   25  pub fn get_g_aligner(seq: &[u8], threads: usize) -> Aligner {
   26      let aligner = Aligner {
   27          mapopt: MapOpt {
   28              a: 2,
   29              ..Aligner::builder().map_hifi().mapopt
   30          },
   31          ..Aligner::builder().map_hifi()
   32      }
   33      .with_index_threads(threads)
   34      .with_cigar()
   35      .with_seq(seq);

**Comment by holtjma** [comment]
Ah, that will probably work, but I will need to try it of course.  I'll leave this open in case Joseph has some other ideas for managing this edge case.

**Comment by jguhlin** [comment]
I can't add anything more. I've added some docs on all the different MapOpts from minimap source code, so that should help. Cheers

**Comment by holtjma** [comment]
Hi @jguhlin,

> I've added some docs on all the different MapOpts from minimap source code, so that should help.

Do you have a link for this? I checked docs.rs but couldn't find any updated docs on the options.

Matt

**Comment by jguhlin** [comment]
@holtjma Ah sorry, they are only in the README
https://github.com/jguhlin/minimap2-rs/?tab=readme-ov-file#minimap2-mapping-and-indexing-options

If we turn some into ergonomic functions, they'll show up in docs
